package publish

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// gitHubClient creates repositories and pushes generated sites. One
// repository per website (spec §9.7 Model A).
type gitHubClient struct {
	token string
	http  *http.Client
}

func newGitHubClient(token string) *gitHubClient {
	return &gitHubClient{token: token, http: &http.Client{Timeout: 30 * time.Second}}
}

func (g *gitHubClient) api(ctx context.Context, method, path string, body any) (*http.Response, error) {
	var rdr *bytes.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, err
		}
		rdr = bytes.NewReader(b)
	} else {
		rdr = bytes.NewReader(nil)
	}
	req, err := http.NewRequestWithContext(ctx, method, "https://api.github.com"+path, rdr)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+g.token)
	req.Header.Set("Accept", "application/vnd.github+json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	return g.http.Do(req)
}

// EnsureRepo makes sure owner/name exists, creating a private repository if
// needed. Works for both user and organization owners.
func (g *gitHubClient) EnsureRepo(ctx context.Context, owner, name string) error {
	resp, err := g.api(ctx, "GET", "/repos/"+owner+"/"+name, nil)
	if err != nil {
		return fmt.Errorf("check repo: %w", err)
	}
	resp.Body.Close()
	if resp.StatusCode == http.StatusOK {
		return nil
	}
	if resp.StatusCode != http.StatusNotFound {
		return fmt.Errorf("check repo %s/%s: unexpected status %s", owner, name, resp.Status)
	}

	payload := map[string]any{"name": name, "private": true, "auto_init": false,
		"description": "Static site generated by CMS"}
	// Try as an organization first, then fall back to the authenticated user.
	resp, err = g.api(ctx, "POST", "/orgs/"+owner+"/repos", payload)
	if err != nil {
		return fmt.Errorf("create repo: %w", err)
	}
	resp.Body.Close()
	if resp.StatusCode == http.StatusCreated {
		return nil
	}
	resp, err = g.api(ctx, "POST", "/user/repos", payload)
	if err != nil {
		return fmt.Errorf("create repo: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusCreated {
		return nil
	}
	var msg struct {
		Message string `json:"message"`
	}
	_ = json.NewDecoder(resp.Body).Decode(&msg)
	return fmt.Errorf("create repo %s/%s: %s %s", owner, name, resp.Status, msg.Message)
}

// Push clones the repo, replaces its contents with siteDir, commits and
// pushes to main. Returns the commit hash. Cloning (rather than force-push
// from scratch) preserves deployment history in git.
func (g *gitHubClient) Push(ctx context.Context, repo, siteDir, message string) (string, error) {
	workDir, err := os.MkdirTemp("", "cms-push-*")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(workDir)

	// Authenticate via header so the token never lands in .git/config or logs.
	authHeader := "AUTHORIZATION: basic " +
		base64.StdEncoding.EncodeToString([]byte("x-access-token:"+g.token))
	gitAuth := []string{"-c", "http.extraheader=" + authHeader,
		"-c", "user.name=CMS Publisher", "-c", "user.email=publisher@cms.local"}
	remote := "https://github.com/" + repo + ".git"

	run := func(dir string, args ...string) (string, error) {
		cmd := exec.CommandContext(ctx, "git", append(gitAuth, args...)...)
		cmd.Dir = dir
		var out bytes.Buffer
		cmd.Stdout, cmd.Stderr = &out, &out
		err := cmd.Run()
		return strings.TrimSpace(out.String()), err
	}

	if out, err := run(workDir, "clone", "--depth", "1", remote, "."); err != nil {
		// A brand-new repository has no refs to clone; start fresh.
		if !strings.Contains(out, "You appear to have cloned an empty repository") &&
			!strings.Contains(out, "warning: remote HEAD refers to nonexistent ref") {
			if _, err2 := run(workDir, "init", "-b", "main"); err2 != nil {
				return "", fmt.Errorf("git clone: %s: %w", sanitize(out), err)
			}
			if out2, err2 := run(workDir, "remote", "add", "origin", remote); err2 != nil {
				return "", fmt.Errorf("git remote add: %s: %w", sanitize(out2), err2)
			}
		}
	}

	// Replace working tree contents (keep .git).
	entries, err := os.ReadDir(workDir)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if e.Name() == ".git" {
			continue
		}
		if err := os.RemoveAll(filepath.Join(workDir, e.Name())); err != nil {
			return "", err
		}
	}
	if err := copyDir(siteDir, workDir); err != nil {
		return "", fmt.Errorf("copy site into repo: %w", err)
	}

	if out, err := run(workDir, "add", "-A"); err != nil {
		return "", fmt.Errorf("git add: %s: %w", sanitize(out), err)
	}
	if out, err := run(workDir, "commit", "-m", message); err != nil {
		if strings.Contains(out, "nothing to commit") {
			hash, _ := run(workDir, "rev-parse", "HEAD")
			return hash, nil
		}
		return "", fmt.Errorf("git commit: %s: %w", sanitize(out), err)
	}
	if out, err := run(workDir, "push", "origin", "HEAD:main"); err != nil {
		return "", fmt.Errorf("git push: %s: %w", sanitize(out), err)
	}
	hash, err := run(workDir, "rev-parse", "HEAD")
	if err != nil {
		return "", fmt.Errorf("git rev-parse: %w", err)
	}
	return hash, nil
}

// sanitize trims git output for storage in error messages.
func sanitize(s string) string {
	if len(s) > 500 {
		s = s[:500] + "…"
	}
	return s
}

func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
}
